### ISSUE TITLE
Files are successfully converted but fail post processing test

### ISSUE THREAD

**Issue by ottodoesntknow** [Unmanic/unmanic#149]
### Description

All converted files fail the post processing test, without additional context on why it fails.
At first I thought this was a permission issue, but I checked and my library has the correct permissions and owners.

### Steps to Reproduce

Video Encoding disabled and Audio Encoding enabled but just for Audio Stream Cloning. Other settings are left as default.

**Expected behavior:** Converted files passing post processing test, or at least giving you details on why the test failed.

**Actual behaviour:** Converted files fail the post processing test, without additional context on why it fails.

**Reproduces how often:** 100%, it happens with all my library

### Versions

Unmanic Version - 0.0.1+974ad93
Unmanic is running in a Docker container on a Ubuntu 20.04.2 LTS PC

### Installation Method Used

Docker Compose

### Additional Information

Here are the logs for the issue described:
```
2021-02-03T18:36:15:INFO:Unmanic.Worker-1 - [FORMATTED] - Successfully converted file '/library/movies/collection/Pequeños Detalles (2021)/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC.mp4'
2021-02-03T18:36:15:INFO:Unmanic.Worker-1 - [FORMATTED] - Worker-1 finished job - /library/movies/collection/Pequeños Detalles (2021)/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC.mp4
2021-02-03T18:36:16:INFO:Unmanic.PostProcessor - [FORMATTED] - Post-processing task - /library/movies/collection/Pequeños Detalles (2021)/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC.mp4
2021-02-03T18:36:17:WARNING:Unmanic.PostProcessor - [FORMATTED] - Encoded file failed post processing test '/tmp/unmanic/unmanic_file_conversion-1612373507.161271/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC-1612373507.1612842.mkv'
2021-02-03T18:36:17:DEBUG:Unmanic.PostProcessor - [FORMATTED] - Writing task history log.
2021-02-03T18:36:17:ERROR:Unmanic.PostProcessor - [FORMATTED] - Exception in method write_history_log - ('/library/movies/collection/Pequeños Detalles (2021)/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC.mkv', {'error': {'code': -2, 'string': 'No such file or directory'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/postprocessor.py", line 219, in write_history_log
    destination_file_probe = self.ffmpeg.file_probe(destination_data['abspath'])
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/ffmpeg.py", line 156, in file_probe
    probe_info = unffmpeg.Info().file_probe(vid_file_path)
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/unffmpeg/info.py", line 55, in file_probe
    return cli.ffprobe_file(vid_file_path)
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/unffmpeg/lib/cli.py", line 67, in ffprobe_file
    raise FFProbeError(vid_file_path, info)
unmanic.libs.unffmpeg.exceptions.ffprobe.FFProbeError: ('/library/movies/collection/Pequeños Detalles (2021)/Pequeños Detalles (2021) - WEBRIP-1080P X265 AAC.mkv', {'error': {'code': -2, 'string': 'No such file or directory'}})
2021-02-03T18:36:17:DEBUG:Unmanic.History - [FORMATTED] - Task dump probe data for destination file does not exist possibly due to task failure
```

**Comment by Josh5** [comment]
What filesystem is your library's disk partition formatted with?

**Comment by ottodoesntknow** [comment]
My library is located in an external NTFS disk and Unmanic config and cache folder is in my internal ext4 disk.

**Comment by Josh5** [comment]
Thanks. I will take a look when I get time.

Is there any way you can test this with a library that is not on an NTFS drive?

**Comment by ottodoesntknow** [comment]
Sorry for not answering earlier, I missed the GitHub notification. I installed the most recent Docker build but I cannot longer reproduce this bug, as I get the #90 bug.

**Comment by Josh5** [comment]
Marking as resolved
