### ISSUE TITLE
Python3.9 Support 

### ISSUE THREAD

**Issue by martadinata666** [Unmanic/unmanic#195]
### Description

Unmanic running but throws error on foreman and worker

### Steps to Reproduce

1. Build unmanic
2. Run unmanic

**Expected behavior:** 
Worker run like using python 3.7

### Versions
```
Debian sid dcoker using python 3.9
```

### Installation Method Used

Personal docker build, work before rebase to debian sid. As debian sid default to python 3.9 and debian buster default to python 3.7

### Error Log
```
unmanic_app.1.sc1vdsdv00m9@homelab    | Starting migrations
unmanic_app.1.sc1vdsdv00m9@homelab    | There is nothing to migrate
unmanic_app.1.sc1vdsdv00m9@homelab    | Exception in thread Foreman:
unmanic_app.1.sc1vdsdv00m9@homelab    | Traceback (most recent call last):
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
unmanic_app.1.sc1vdsdv00m9@homelab    |     self.run()
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/home/debian/.local/lib/python3.9/site-packages/unmanic-0.0.9-py3.9.egg/unmanic/libs/foreman.py", line 456, in run
unmanic_app.1.sc1vdsdv00m9@homelab    |     self.init_worker_threads()
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/home/debian/.local/lib/python3.9/site-packages/unmanic-0.0.9-py3.9.egg/unmanic/libs/foreman.py", line 397, in init_worker_threads
unmanic_app.1.sc1vdsdv00m9@homelab    |     if not self.worker_threads[thread].isAlive():
unmanic_app.1.sc1vdsdv00m9@homelab    | AttributeError: 'WorkerThread' object has no attribute 'isAlive'
unmanic_app.1.sc1vdsdv00m9@homelab    | Exception in thread Thread-2:
unmanic_app.1.sc1vdsdv00m9@homelab    | Traceback (most recent call last):
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
unmanic_app.1.sc1vdsdv00m9@homelab    |     self.run()
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/home/debian/.local/lib/python3.9/site-packages/watchdog/observers/api.py", line 199, in run
unmanic_app.1.sc1vdsdv00m9@homelab    |     self.dispatch_events(self.event_queue, self.timeout)
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/home/debian/.local/lib/python3.9/site-packages/watchdog/observers/api.py", line 372, in dispatch_events
unmanic_app.1.sc1vdsdv00m9@homelab    |     handler.dispatch(event)
unmanic_app.1.sc1vdsdv00m9@homelab    |   File "/home/debian/.local/lib/python3.9/site-packages/watchdog/events.py", line 282, in dispatch
unmanic_app.1.sc1vdsdv00m9@homelab    |     self.event_dispatch_map[event.event_type](event)
unmanic_app.1.sc1vdsdv00m9@homelab    | AttributeError: 'EventHandler' object has no attribute 'event_dispatch_map'


```

**Comment by Josh5** [comment]
Cheers.

I'll hold off on this until the dev-plugins branch is merged. There are way too many conflicting changes
