### ISSUE TITLE
DataTables give Invalid JSON response

### ISSUE THREAD

**Issue by abamblett** [Unmanic/unmanic#241]
### Description

Have been experiencing an issue on the latest version when loading Data Panels.  Specifically, clicking Data Panels results in an error popup that says "DataTables warning: table id=history_completed_tasks_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

I took a look at the logs, and found the following entry that occurs every time the File Size Metrics plugin is called:

```
2021-10-05T00:19:40:ERROR:Unmanic.Plugin.file_size_metrics - Failed to save historic data to database.
Traceback (most recent call last):
  File "/config/.unmanic/plugins/file_size_metrics/lib/history.py", line 250, in save_source_item
    new_historic_task = HistoricTasks.create(
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6346, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6556, in save
    pk = self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6313, in insert
    return ModelInsert(cls, cls._normalize_data(__data, insert))
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 7269, in __init__
    if self.model._meta.database.returning_clause:
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 447, in __getattr__
    raise AttributeError('Cannot use uninitialized Proxy.')
AttributeError: Cannot use uninitialized Proxy.
2021-10-05T00:19:40:ERROR:Unmanic.Plugin.file_size_metrics - Failed to create source size entry for this file
```

I turned on debugging and the error generated the following also:

```
2021-10-05T11:24:32:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'frontend.panel' plugin runner 'file_size_metrics'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 276, in execute_plugin_runner
    runner(data)
  File "/config/.unmanic/plugins/file_size_metrics/plugin.py", line 207, in render_frontend_panel
    data['content'] = get_historical_data(data)
  File "/config/.unmanic/plugins/file_size_metrics/plugin.py", line 51, in get_historical_data
    results = data.prepare_filtered_historic_tasks(request_dict)
  File "/config/.unmanic/plugins/file_size_metrics/lib/history.py", line 194, in prepare_filtered_historic_tasks
    records_total_count = self.get_total_historic_task_list_count()
  File "/config/.unmanic/plugins/file_size_metrics/lib/history.py", line 53, in get_total_historic_task_list_count
    return query.count()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2184, in count
    return Select([clone], [fn.COUNT(SQL('1'))]).scalar(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2169, in scalar
    row = self.tuples().peek(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2156, in peek
    rows = self.execute(database)[:n]
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1978, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2150, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 447, in __getattr__
    raise AttributeError('Cannot use uninitialized Proxy.')
AttributeError: Cannot use uninitialized Proxy.
```

Maybe my database is simply corrupt?

### Steps to Reproduce

1. Open Unmanic
2. Have the File Size Metrics Plugin Active
3. Click "Data Panels" in the left bar.

**Expected behavior:**
Display file size metrics for all processed files

**Actual behaviour:**
The reported error appears.  No items populate under entries.

**Reproduces how often:**
100% (for me)

### Versions

0.1.1+68717c4

### Installation Method Used

Docker running on Unraid 6.9.2 (josh5/unmanic)

**Comment by dhruvinsh** [comment]
If any one come across the same issue, I had a similar issue, and restarting the docker container (which I had) works fine.
