### ISSUE TITLE
Unmanic has stopped processing tasks as it has detected an incompatible plugin enabled on one of your libraries

### ISSUE THREAD

**Issue by SuberSeb** [Unmanic/unmanic#357]
### Description

Got this error while processing tasks - "Unmanic has stopped processing tasks as it has detected an incompatible plugin enabled on one of your libraries - Audio Encoder AAC". Also this repeated for all other my plugins, e.g. Sonarr plugin, Radarr plugin, nvenc h265 plugin, etc. All plugins were updated and reinstalled, it doesn't help.

### Steps to Reproduce

Hard to reproduce, the problem occurs on its own. 

**Expected behavior:** No error.

**Actual behaviour:** Got error.

**Reproduces how often:** Every time when I'm trying to rescan my media folder (a lot of files, more than 10 terabytes).

### Versions

Version: [0.2.3~b517463]

### Installation Method Used

Docker

### Additional Information

Error in logs (very strange):

2022-08-14T09:08:28:ERROR:Unmanic.PluginsHandler - [FORMATTED] - Exception while fetching plugin info for notify_radarr: - [Errno 24] Too many open files: '/config/.unmanic/plugins/notify_radarr/info.json'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/plugins.py", line 713, in get_incompatible_enabled_plugins
    plugin_info = self.get_plugin_info(record.get('plugin_id'))
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/plugins.py", line 210, in get_plugin_info
    with open(info_file) as json_file:
OSError: [Errno 24] Too many open files: '/config/.unmanic/plugins/notify_radarr/info.json'

2022-08-14T09:09:33:ERROR:Unmanic.PluginsHandler - [FORMATTED] - Exception while fetching plugin info for postprocessor_script: - [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/plugins.py", line 713, in get_incompatible_enabled_plugins
    plugin_info = self.get_plugin_info(record.get('plugin_id'))
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/plugins.py", line 211, in get_plugin_info
    plugin_info = json.load(json_file)
OSError: [Errno 9] Bad file descriptor

**Comment by SuberSeb** [comment]
Need to clarify that this problem happens not every time when I'm making rescan of library. Yesterday at some time I haven't any issues but today's morning it happened again. Not sure why this happening.
