### ISSUE TITLE
Filenames with german "Umlaute" (Ä Ö Ü) are leading to a library scanning error

### ISSUE THREAD

**Issue by FleischKarussel** [Unmanic/unmanic#358]
Hello guys and gals,

I've stumbled upon a small error with unicode filename handling I guess?

### Description

Filenames with german "Umlaute" (Ä Ö Ü) are leading to an filename scanning error.
I've found #19 with a similar error, but the code, that consisted of a list of characters, is not included in the current release anymore.
Is this related?

This is one of a few examples with different "Umlaute" cases.

`2022-08-15T10:33:28:ERROR:Unmanic.TaskHandler - [FORMATTED] - Exception in processing scheduledtasks - 'utf-8' codec can't encode character '\udcf6' in position 103: surrogates not allowed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/taskhandler.py", line 93, in process_scheduledtasks_queue
    if self.add_path_to_task_queue(pathname, library_id, priority_score=priority_score):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/taskhandler.py", line 152, in add_path_to_task_queue
    if self.check_if_task_exists_matching_path(abspath):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/taskhandler.py", line 137, in check_if_task_exists_matching_path
    if existing_task_query.count() > 0:
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1918, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2196, in count
    return Select([clone], [fn.COUNT(SQL('1'))]).scalar(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1918, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2181, in scalar
    row = self.tuples().peek(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1918, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2168, in peek
    rows = self.execute(database)[:n]
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1918, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1989, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2162, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3190, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3177, in execute_sql
    cursor.execute(sql, params or ())
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 103: surrogates not allowed`

### Steps to Reproduce

1. Rescanning the library

**Expected behavior:** [What you expect to happen]

No errors and stuff ;)

**Actual behaviour:** [What actually happens]

The worker is in state "Waiting for another task..." infinitly, even though some other files are in queue.
Maybe unrelated and a completely different error, but this lead me to the error in the logs.

**Reproduces how often:** [What percentage of the time does it reproduce?]

every library scan, so 100%

### Versions

Version: 0.2.3~b517463

### Installation Method Used

Docker
Media Library via host mounts on the same machine

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by eihns** [comment]
I have no idea about this, but its not a german umlaut.

https://github.com/ocrmypdf/OCRmyPDF/issues/835

`\udcf6 or U+DCF6 is not an umlaut, it is a Unicode surrogate character, usually used to transmit UCS-4 characters inside UTF-16. They are not permitted in normal Unicode strings. ŭ is U+00FC, or the equivalently the sequence U+0308 U+0075.

`
