### ISSUE TITLE
Peewee Migration Failure

### ISSUE THREAD

**Issue by cshyjak** [Unmanic/unmanic#368]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect: Yes

Remember that these are some guidelines, use your best judgement.

### Description

Receiving an error when starting unmanic on the second (or subsequent launches). The first launch works properly.

### Steps to Reproduce

1. Pull latest from staging branch
2. Compile using instructions from repo
```
python3 ./setup.py install --user
```
4. Launch unmanic
```
unmanic
```
5. Kill running process
6. Re-launch unmanic
7. Error is displayed

**Expected behavior:** [What you expect to happen]
Unmanic launches successfully on each attempt

**Actual behaviour:** [What actually happens]

Error received:

```
2022-10-18T20:45:02:INFO:Unmanic.UnmanicLogger - Initialising file logger. All further logs should output to the 'unmanic.log' file
Traceback (most recent call last):
  File "/home/craig/.local/bin/unmanic", line 33, in <module>
    sys.exit(load_entry_point('unmanic===0.2.3-ckshyjak', 'console_scripts', 'unmanic')())
  File "/home/craig/.local/lib/python3.10/site-packages/unmanic-0.2.3_ckshyjak-py3.10.egg/unmanic/service.py", line 308, in main
    service.run()
  File "/home/craig/.local/lib/python3.10/site-packages/unmanic-0.2.3_ckshyjak-py3.10.egg/unmanic/service.py", line 242, in run
    self.db_connection = init_db(settings.get_config_path())
  File "/home/craig/.local/lib/python3.10/site-packages/unmanic-0.2.3_ckshyjak-py3.10.egg/unmanic/service.py", line 74, in init_db
    migrations.update_schema()
  File "/home/craig/.local/lib/python3.10/site-packages/unmanic-0.2.3_ckshyjak-py3.10.egg/unmanic/libs/db_migrate.py", line 119, in update_schema
    self.router.migrator.create_table(model)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/craig/.local/lib/python3.10/site-packages/peewee_migrate-1.6.1-py3.10.egg/peewee_migrate/router.py", line 83, in migrator
    self.run_one(name, migrator)
  File "/home/craig/.local/lib/python3.10/site-packages/peewee_migrate-1.6.1-py3.10.egg/peewee_migrate/router.py", line 166, in run_one
    migrate(migrator, self.database, fake=fake)
  File "<string>", line 49, in migrate
  File "/home/craig/.local/lib/python3.10/site-packages/peewee-3.15.3-py3.10.egg/peewee.py", line 3785, in get_columns
    return [ColumnMetadata(r[1], r[2], not r[3], bool(r[5]), table, r[4])
TypeError: 'Mock' object is not iterable
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every subsequent launch

### Versions

OS="Ubuntu 22.04.1 LTS"
Python=“Python 3.10.6”
Unmanic=“[staging Branch](https://github.com/Unmanic/unmanic/commit/c2e4906707e1551cc9de61497119c643e39f4773)”

### Installation Method Used

Manually Installed

### Additional Information

N/A

**Comment by Josh5** [comment]
Did you break Unmanic staging with your PR? 😅

**Comment by cshyjak** [comment]
100% it was me…. It’s odd that it runs without problems the first time.  I’m honestly not much of a python dev but have been trying to figure out what’s going on.  Any pointers are more than welcome.

**Comment by Josh5** [comment]
All good. Try loosening the dependencies for anything peewee related with >=
