### ISSUE TITLE
Ubuntu 22.04 with Python 3.10 does not work

### ISSUE THREAD

**Issue by JSylvia007** [Unmanic/unmanic#379]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Had a working system on Ubuntu 20.04, but upgraded finally to 22.04.1.  Can't get unmanic to work more than once.  Started a completely fresh install and Python 3.10 won't work with the version of peewee_migrate that's required.  If I trick it, and get it to install the latest peewee_migrate (1.6.3) then unmanic will start ONCE, and then fail every time after that.

### Steps to Reproduce

1. Create clean home directory
2. su to unmanic user
3. python3 -m pip install unmanic
4. unmanic (successful start)
5. Press Ctrl + C
6. unmanic (dies)

**Expected behavior:**
Should work with Python 3.10, should launch successfully more than a single time.

**Actual behaviour:**
Dies immediately after second launch.

**Reproduces how often:**
100% reproducable.

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
Version: [0.2.3~b517463]

### Installation Method Used

Manually installed via pip.

### Additional Information
```
unmanic@plex01:~$ python3 -m unmanic
2022-11-26T14:08:10:INFO:Unmanic.UnmanicLogger - Initialising file logger. All further logs should output to the 'unmanic.log' file
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/unmanic/.local/lib/python3.10/site-packages/unmanic/__main__.py", line 36, in <module>
    main()
  File "/opt/unmanic/.local/lib/python3.10/site-packages/unmanic/service.py", line 308, in main
    service.run()
  File "/opt/unmanic/.local/lib/python3.10/site-packages/unmanic/service.py", line 242, in run
    self.db_connection = init_db(settings.get_config_path())
  File "/opt/unmanic/.local/lib/python3.10/site-packages/unmanic/service.py", line 74, in init_db
    migrations.update_schema()
  File "/opt/unmanic/.local/lib/python3.10/site-packages/unmanic/libs/db_migrate.py", line 119, in update_schema
    self.router.migrator.create_table(model)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/unmanic/.local/lib/python3.10/site-packages/peewee_migrate/router.py", line 83, in migrator
    self.run_one(name, migrator)
  File "/opt/unmanic/.local/lib/python3.10/site-packages/peewee_migrate/router.py", line 166, in run_one
    migrate(migrator, self.database, fake=fake)
  File "<string>", line 49, in migrate
  File "/usr/local/lib/python3.10/dist-packages/peewee.py", line 3808, in get_columns
    return [ColumnMetadata(r[1], r[2], not r[3], bool(r[5]), table, r[4])
TypeError: 'Mock' object is not iterable
```

**Comment by Josh5** [comment]
Install from staging branch
