### ISSUE TITLE
Cannot import name 'hashable' from 'collections'

### ISSUE THREAD

**Issue by ShrimpyChips** [Unmanic/unmanic#389]
I'm trying to install unmanic for the first time. This is on a windows 11 machine. I'm running python 3.11. I got everything to install via pip. Here is the issue when running unmanic:

`Microsoft Windows [Version 10.0.22621.1265]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>unmanic
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Scripts\unmanic.exe\__main__.py", line 4, in <module>
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\site-packages\unmanic\service.py", line 40, in <module>
    from unmanic.libs.db_migrate import Migrations
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\site-packages\unmanic\libs\db_migrate.py", line 37, in <module>
    from peewee_migrate import Router
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\site-packages\peewee_migrate\__init__.py", line 36, in <module>
    from .router import Migrator, Router # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\site-packages\peewee_migrate\router.py", line 12, in <module>
    from peewee_migrate.auto import diff_many, NEWLINE
  File "C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\site-packages\peewee_migrate\auto.py", line 2, in <module>
    from collections import Hashable, OrderedDict
ImportError: cannot import name 'Hashable' from 'collections' (C:\Users\james\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)`

Based on the forum post here on stack exchange this just seems to be an issue with some wording:

https://stackoverflow.com/questions/71618317/importing-tronweb-shows-import-error-cannot-import-name-hashable-from-collec

Can I fix this on my own by modifying an import instruction somewhere?

**Comment by Josh5** [comment]
Install from the staging branch which has a fix for this
