### ISSUE TITLE
Request: Docker health check

### ISSUE THREAD

**Issue by ninjamonkey198206** [Unmanic/unmanic#391]
The most common issue I come across when using this via docker is the workers stalling. I don't know if it happens on a manual install.

It would be great to have a monitor of sorts to watch the workers and restart them if they hang, or at least have a method to determine that they've hung and place the container in an unhealthy state, which could then be used to automatically restart the container via any number of tools.

**Comment by Josh5** [comment]
> The most common issue I come across when using this via docker is the workers stalling. I don't know if it happens on a manual install.
> 
> It would be great to have a monitor of sorts to watch the workers and restart them if they hang, or at least have a method to determine that they've hung and place the container in an unhealthy state, which could then be used to automatically restart the container via any number of tools. 

Could you elaborate on what a stalled worker looks like? Do you mean the command is not exiting?

**Comment by ninjamonkey198206** [comment]
What I mean is when there is a list of files to process, but the workers don't pick them up and start, they just spin around and around and around like a record baby, right round... Sorry, got sidetracked.

They stay in that state until the container is restarted.

**Comment by ninjamonkey198206** [comment]
It can happen during a run on an existing list, or after new files are added when the list was previously empty, and for testing purposes I've left it in that state overnight and it remained in that stalled state.

Other functions work fine, manual scans, changing settings, removing files from the lists, etc.

**Comment by ninjamonkey198206** [comment]
It may not be the workers themselves, it may be whatever kick-starts the process of pulling a new task, if that makes sense.

**Comment by Josh5** [comment]
Sounds like something about either the worker or the plugin is throwing an exception and that could be a bug in Unmanic. Could you provide some logs when this is happening.

**Comment by ninjamonkey198206** [comment]
I will try to dig some up.

**Comment by ninjamonkey198206** [comment]
As luck would have it, it was doing it when I opened up the web ui just a short while ago.
Copied the current unmanic and tornado log files (don't know what tornado is) and I'm going to browse through to just before it started spazzing out.

**Comment by ninjamonkey198206** [comment]
Looks like there is an issue creating the temp file/folder sometimes.

unmanic.log snippet:
```text
2023-03-05T11:33:25:INFO:Unmanic.PluginsHandler - [FORMATTED] - Repo cache file '/config/.unmanic/plugins/repo-272297248206145197564139734001412161930.json'.
2023-03-05T11:33:37:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2023-03-05T12:33:39:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2023-03-05T13:33:41:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2023-03-05T14:33:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Checking for updates to plugin repos
2023-03-05T14:33:27:INFO:Unmanic.PluginsHandler - [FORMATTED] - Repo cache file '/config/.unmanic/plugins/repo-272297248206145197564139734001412161930.json'.
2023-03-05T14:33:42:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2023-03-05T15:33:44:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2023-03-05T15:53:10:INFO:Unmanic.EventProcessor - [FORMATTED] - Detected 'created' event on file path '/movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv'
2023-03-05T15:53:10:INFO:Unmanic.TaskHandler - [FORMATTED] - Adding inotify job to queue - /movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv
2023-03-05T15:53:11:INFO:Unmanic.Foreman - [FORMATTED] - Processing item - /movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv
2023-03-05T15:53:12:INFO:Unmanic.Derp-Worker-1 - [FORMATTED] - Picked up job - /movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv
2023-03-05T15:53:12:ERROR:Unmanic.Derp-Worker-1 - [FORMATTED] - Exception in processing job with Derp-Worker-1: - [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 122, in run
    self.__process_task_queue_item()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 226, in __process_task_queue_item
    success = self.__exec_worker_runners_on_set_task()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 380, in __exec_worker_runners_on_set_task
    success = self.__exec_command_subprocess(data)
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 577, in __exec_command_subprocess
    common.ensure_dir(data.get("file_out"))
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/common.py", line 138, in ensure_dir
    os.makedirs(directory)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
2023-03-05T15:53:12:INFO:Unmanic.Derp-Worker-1 - [FORMATTED] - Picked up job - /movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv
2023-03-05T15:53:13:ERROR:Unmanic.Derp-Worker-1 - [FORMATTED] - Exception in processing job with Derp-Worker-1: - [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 122, in run
    self.__process_task_queue_item()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 226, in __process_task_queue_item
    success = self.__exec_worker_runners_on_set_task()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 380, in __exec_worker_runners_on_set_task
    success = self.__exec_command_subprocess(data)
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 577, in __exec_command_subprocess
    common.ensure_dir(data.get("file_out"))
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/common.py", line 138, in ensure_dir
    os.makedirs(directory)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
2023-03-05T15:53:13:INFO:Unmanic.Derp-Worker-1 - [FORMATTED] - Picked up job - /movies/Ronin_(1998)/Ronin_(1998)_Remux-1080p.mkv
2023-03-05T15:53:14:ERROR:Unmanic.Derp-Worker-1 - [FORMATTED] - Exception in processing job with Derp-Worker-1: - [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 122, in run
    self.__process_task_queue_item()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 226, in __process_task_queue_item
    success = self.__exec_worker_runners_on_set_task()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 380, in __exec_worker_runners_on_set_task
    success = self.__exec_command_subprocess(data)
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/workers.py", line 577, in __exec_command_subprocess
    common.ensure_dir(data.get("file_out"))
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/common.py", line 138, in ensure_dir
    os.makedirs(directory)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-vmibc-1678053190'
```
After this it just repeats unendingly until the container is restarted. Somewhere around 24MB of that on repeat.

**Comment by ninjamonkey198206** [comment]
Relevant docker-compose info:
```text
# unmanic
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    hostname: ${UNMANIC_HOST}
    domainname: ${DOMAIN}
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NVIDIA_VISIBLE_DEVICES: all
    networks:
      media:
        ipv4_address: ${UNMANIC_IP}
    ports:
      - ${UNMANIC_EXP_PORT}:8888
    volumes:
      - unmanic_data:/config
      - /ZFS2/TVShows:/tv
      - /ZFS2/Movies:/movies
      - /dev/shm/unmanic:/tmp/unmanic
    runtime: nvidia
```

**Comment by ninjamonkey198206** [comment]
If there's anything else you need, just let me know.

**Comment by ulintlicker** [comment]
Bump


I have this same issue

Log:

2025-10-07T19:58:39:INFO:Unmanic.Worker - Picked up job - /library/tv/High Potential/Season 2/High.Potential.S02E04.720p.HDTV.x264-SYNCOPY.mkv

2025-10-07T19:58:40:ERROR:Unmanic.Worker - [FORMATTED] - Exception in processing job with Vuzashi-Worker-1: - [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-ggttx-1759882368'

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/workers.py", line 438, in run

    self.__process_task_queue_item()

  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/workers.py", line 538, in __process_task_queue_item

    success = self.__exec_worker_runners_on_set_task()

  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/workers.py", line 731, in __exec_worker_runners_on_set_task

    success = self.__exec_command_subprocess(data)

  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/workers.py", line 916, in __exec_command_subprocess

    common.ensure_dir(data.get("file_out"))

  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/common.py", line 146, in ensure_dir

    os.makedirs(directory)

  File "/usr/lib/python3.10/os.py", line 225, in makedirs

    mkdir(name, mode)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/unmanic/unmanic_file_conversion-ggttx-1759882368'


Repeats forever until i restart the docker container
